---
language: python
python: 2.7

install:
  - pip install ansible
  - printf '[defaults]\nroles_path = ../\n' > ansible.cfg

script:
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
